### ISSUE TITLE
Peer to peer code review 

### ISSUE THREAD

**Issue by jaferIdrees** [VitorGuedesMadeira/Capstone#2]
### Hello Vitor,
You have a great work till the moment, from our side we found the below to points that you can work on:

- The mobile menu should be aligned with the main title as per the original design. 🍒 
- The close button for the mobile menu in the about page disappears when you open the menu. 👍 

Highlights:

- You followed the original design perfectly. ✔️ 
- There are no bugs in your code. 💯 
- You choose a perfect subject for such a design. 👍

**Comment by VitorGuedesMadeira** [comment]
It was fixed already! Thanks for the feedback! ✔️
